SemanticPass: Descend into subnodes earlier in sa_MemberExpression
This will allow to unify subnode processing in all branches in
sa_MemberExpression.

Note this slightly changes language semantics. For example, programs
like this:

    const c = m.c;

now report:

    Error: m is not defined (UNDEFINED)

instead of:

    Error: variable 'c' is not exported by module m (NOT-EXPORTED)

I claim the new message is actually more logical.