package.json: Use `moment` ^2.11.1
This ensures we don't hit this bug:

    https://github.com/moment/moment/issues/2841

The bug caused the following test failure:

    2) The Date.parse function Parses a custom-formatted date:

        AssertionError: expected [] to deeply equal [ { winning: true } ]
        + expected - actual

        -[]
        +[
        +  {
        +    "winning": true
        +  }
        +]

        at Assertion.assertEqual (node_modules/chai/lib/chai/core/assertions.js:427:19)
        at Assertion.ctx.(anonymous function) [as equal] (node_modules/chai/lib/chai/utils/addMethod.js:40:25)
        at test/runtime/specs/juttle-spec/modules/date/parse.spec.js:47:50
        at bound (domain.js:287:14)
        at runBound (domain.js:300:12)
        at tryCatcher (node_modules/bluebird/js/main/util.js:26:23)
        at Promise._settlePromiseFromHandler (node_modules/bluebird/js/main/promise.js:507:31)
        at Promise._settlePromiseAt (node_modules/bluebird/js/main/promise.js:581:18)
        at Async._drainQueue (node_modules/bluebird/js/main/async.js:128:12)
        at Async._drainQueues (node_modules/bluebird/js/main/async.js:133:10)
        at Immediate.Async.drainQueues [as _onImmediate] (node_modules/bluebird/js/main/async.js:15:14)